utils::globalVariables(c("country", "region", "income"))

#' Add grouping information of the WDI data to a metric summary
#'
#' @param metric_summary A data frame containing the calculated diagnostic indices generated by any of the following functions:
#' \code{\link{compute_variation}}, \code{\link{compute_trend_shape_features}}, \code{\link{compute_temporal_features}}, or \code{\link{compute_diagnostic_indices}}
#' @param wdi_data A data frame of the indicator data generated by \code{\link{get_wdi_data}}
#'
#' @returns A data frame containing the calculated diagnostic indices and the grouping variables in the WDI data set.
#' @export
#'
#' @examples
#' pm_data <- get_wdi_data(indicator = "EN.ATM.PM25.MC.M3")
#' pm_diagnostic_metrics <- compute_diagnostic_indices(pm_data, group_var = "region")
#' pm_diagnostic_metrics_group <- add_group_info(metric_summary = pm_diagnostic_metrics,pm_data)
add_group_info <- function(metric_summary, wdi_data){
  # Check if 'country' exists in metric_summary
  if (!"country" %in% names(metric_summary)) {
    stop("The required column 'country' is missing in the metric_summary dataset.")
  }
  country_groups <- metric_summary |>
    dplyr::left_join(
      wdi_data |> dplyr::select(country, region, income),
      by = "country",
      multiple = "first"
    ) |>
    dplyr::select(country, region, income, dplyr::everything())

  return(country_groups)
}
