#' Compute dissimilarity between pair of countries
#' Calculate pairwise dissimilarities and convert the output to matrix.
#'
#' @param wdi_data A data frame of the indicator data generated by \code{\link{get_wdi_data}}
#' @param index An optional character string specifying the indicator code
#' Defaults to `NULL`
#' @param metric A character string specifying the dissimilarity metric to use
#' Defaults to `"euclidean"`
#'
#' @returns A matrix of pairwise dissimilarities between countries.
#' @export
#'
#' @examples
#' pm_diss_mat <- compute_dissimilarity(pm_data)
compute_dissimilarity <- function(wdi_data, index = NULL, metric = "euclidean"){
  # Identify the name of the variable in the wdi data that contains the country-year value as index
  if(is.null(index)) {
    index_var <- attr(wdi_data, "index_var")
    index = index_var[1]
  }

  # verify that the country, year and index columns exist in the given wdi_data
  #if the columns exist, proceed, else paste the error message
  cols <- c("country", "year", index)
  missing_cols <- cols[!cols %in% names(wdi_data)]
  if (length(missing_cols) > 0){
    stop(paste("The required column(s) are missing in the provided dataset:",
               paste(missing_cols, collapse = ", ")))
  }

  # convert the wdi_data to a wider form
  data_wide <- wdi_data |>
    dplyr::select(.data$country, .data$year, tidyselect::all_of(index)) |>
    tidyr::pivot_wider(
      names_from = year,
      values_from = tidyselect::all_of(index)
    ) |>
    tibble::column_to_rownames("country") |> # set columns to row names
    as.data.frame()

  # dissimilarity distance using daisy
  dist <- cluster::daisy(data_wide, metric = metric)

  # convert the dist to matrix
  dist_mat <- as.matrix(dist)

  # set the dist of a country to itself to NA
  diag(dist_mat) <- NA

  return(dist_mat)
}
