
if(getRversion() >= "3.5") utils::globalVariables(c("country", "year"))

#' compute daisy dissimilarity distance to WDI data
#' compute dissimilarity distance and convert the output to matrix
#' @param data A tibble either generated by \code{\link{cache_wdi_data}} or downloaded from other world bank-hosted databases
#' @param index Any indicator of choice or the name of the variable containing the observational data
#' @param metric A default euclidean metric, if otherwise, specify the type of method to calculate dissimilarity distance
#'
#' @return A matrix indicating the pairwise comparisons
#' @seealso [cache_wdi_data()] to load/cache the data
#' @author Oluwayomi Akinfenwa - <\email{yomiolaitan03@gmail.com}>
#' @export
#'
#' @examples
#' dist_mat <- compute_dissimilarity(data = pisa_data, index = "LO.PISA.MAT")


compute_dissimilarity <- function(data, index, metric = "euclidean"){
  # check that the country, year, and the specified index column exist in the given data
  #if it does proceed, else flag the error message
  cols <- c("country", "year", index)
  missing_cols <- cols[!cols %in% names(data)]
  if (length(missing_cols) > 0){
    stop(paste("The required column(s) are missing in the provided dataset:",
               paste(missing_cols, collapse = ", ")))
  }

  # convert the data to a wider form
  data_wide <- data |>
    dplyr::select(country, year, tidyselect::all_of(index)) |>
    tidyr::pivot_wider(
      names_from = year,
      values_from = tidyselect::all_of(index)
    ) |>
    tibble::column_to_rownames("country") |> # set columns to row names
    as.data.frame()

  # dissimilarity distance using daisy
  dist <- cluster::daisy(data_wide, metric = metric)

  # convert the dist to matrix
  dist_mat <- as.matrix(dist)

  # set the dist of a country to itself to NA
  diag(dist_mat) <- NA

  return(dist_mat)
}
