utils::globalVariables(c("year", "country1", "dist", "group1",
                    "group2", "avg_dist", "a", "b", "sil_width"))

#' Compute variation features
#'
#' Calculates average dissimilarities between countries, group-wise country dissimilarities, and silhouette widths.
#'
#' @param wdi_data A data frame of the indicator data generated by \code{\link{get_wdi_data}}
#' @param diss_matrix An optional dissimilarity matrix generated by \code{\link{compute_dissimilarity}}
#' @param group_var A grouping variable in the WDI data set (e.g., "region" or "income")
#'
#' @returns A data frame with columns `country`, `group`, `country_avg_dist`, `within_group_dist`, and `sil_width`.
#' @export
#'
#' @examples
#' pm_data <- get_wdi_data(indicator = "EN.ATM.PM25.MC.M3")
#' pm_variation <- compute_variation(pm_data, group_var = "region")
compute_variation <- function(wdi_data, diss_matrix = compute_dissimilarity(wdi_data), group_var) {

  # Convert the dissimilarity distance matrix to a data frame
  diss_df <- as.data.frame(as.table(diss_matrix))
  colnames(diss_df) <- c("country2", "country1", "dist")

  # country2 as the first column because those are columns names and country1 are row names.
  # join the group_data with the diss_df

  # join the grouping information from the wdi_data to the diss_df
  diss_data <- diss_df |>
    dplyr::left_join(
      wdi_data |> dplyr::select(country, tidyselect::all_of(group_var)),
      by = c("country1" = "country"),
      multiple = "first"
    ) |>
    dplyr::left_join(
      wdi_data |> dplyr::select(country, tidyselect::all_of(group_var)),
      by = c("country2" = "country"),
      multiple = "first",
      suffix = c("_1", "_2")
    ) |>
    dplyr::rename(
      group1 = tidyselect::all_of(paste0(group_var, "_1")),
      group2 = tidyselect::all_of(paste0(group_var, "_2"))
    )

  # calculate the country average dist
  country_avg_dist <- diss_data |>
    dplyr::group_by(country1) |>
    dplyr::filter(sum(!is.na(dist)) > 0) |> # Ensure that a country has at least one valid dist
    dplyr::summarise(
      country_avg_dist = mean(dist, na.rm = TRUE),
      .groups = "drop")

  # silhouette calculations

  # for each country1, find the mean of dist if group1 == group2
  a_vals <- diss_data |>
    dplyr::filter(group1 == group2) |>
    dplyr::group_by(country1, group1) |>
    dplyr::filter(sum(!is.na(dist)) > 0) |>  # Ensure that a country has at least one valid dist
    dplyr::summarise(a = mean(dist, na.rm = TRUE),
                     .groups = "drop")

  # for each country1, find the mean of dist if group1 != group2
  neighbour_vals <- diss_data |>
    dplyr::filter(group1 != group2) |>
    dplyr::group_by(country1, group2) |>
    dplyr::filter(sum(!is.na(dist)) > 0) |>  # Ensure that a country has at least one valid dist
    dplyr::summarise(avg_dist = mean(dist, na.rm = TRUE),
                     .groups = "drop")

  # select the group with the min avg_dist
  b_vals <- neighbour_vals |>
    dplyr::group_by(country1) |>
    dplyr::summarise(neighbour = group2[which.min(avg_dist)],
                     b = min(avg_dist, na.rm = TRUE),
                     .groups = "drop")

  # calculate the silhouette score of each country
  variation_scores <- country_avg_dist |>
    dplyr::left_join(a_vals, dplyr::join_by("country1")) |>
    dplyr::left_join(b_vals, dplyr::join_by("country1")) |>
    dplyr::mutate(sil_width = dplyr::if_else(is.na(a),
                                             0, # if a is NA, set sil_width = 0
                                             ((b - a)/ pmax(a, b)))) |> #parrallel max value btw a and b
    dplyr::select(country = country1, group = group1, country_avg_dist,
                  within_group_avg_dist = a, sil_width)


  return(variation_scores)
}
