
if(getRversion() >= "3.5") utils::globalVariables(c("country1", "dist", "group1", "group2", "avg_dist",
                                                    "a", "b", "neighbour", "sil_width"))

#' Compute silhouette analysis to the matrix output of the dissimilarity distance of WDI data
#'
#' @param matrix A matrix generated by \code{\link{compute_dissimilarity}}
#' @param group_data A data frame containing country information and the inherent grouping variable of the data
#' @param group_var An inherent variable of the WDI data as the grouping variable
#'
#' @return A data frame with country, average dissimilarity distance, group, neighbouring group, group_wise average dissimilarity distance, and the sil_width
#' @seealso [compute_dissimilarity()] to compute the matrix
#' @export
#'
#' @examples
#' dist_mat <- compute_dissimilarity(data = pisa_data, index = "LO.PISA.MAT")
#' silhouette_score <- compute_silhouette(matrix = dist_mat,
#'             group_data = country_groups, group_var = "region")
compute_silhouette <- function(matrix, group_data, group_var) {

  # Convert the dissimilarity distance matrix to a data frame
  dist_df <- as.data.frame(as.table(matrix))
  colnames(dist_df) <- c("country2", "country1", "dist")

  # the country2 as the first column because those are columns names and country1 are row names.
  # join the group_data with the dist_df

  # Check if country and group_var columns exist in group_data

  expected_columns <- c("country", group_var)
  missing <- expected_columns[!expected_columns %in% names(group_data)]

  if (length(missing) > 0) {
    stop(paste(
      "The following expected column(s) are missing in group_data:",
      paste(missing, collapse = ", "),
      "\nExpected columns:", paste(expected_columns, collapse = ", "),
      "\nColumns found:", paste(names(group_data), collapse = ", ")
    ))
  }

  dist_data <- dist_df |>
    dplyr::left_join(group_data, dplyr::join_by("country1" == "country")) |>
    dplyr::left_join(group_data, dplyr::join_by("country2" == "country"), suffix = c("_1", "_2")) |>
    dplyr::rename(group1 = dplyr::all_of(paste0(group_var, "_1")),
                  group2 = dplyr::all_of(paste0(group_var, "_2")))

  # calculate the country average dist
  country_avg_dist <- dist_data |>
    dplyr::group_by(country1) |>
    dplyr::summarise(country_avg_dist = mean(dist, na.rm = TRUE),
                     .groups = "drop")

  # silhouette calculations

  # for each country1, find the mean of dist if group1 == group2
  a_vals <- dist_data |>
    dplyr::filter(group1 == group2) |>
    dplyr::group_by(country1, group1) |>
    dplyr::summarise(a = mean(dist, na.rm = TRUE),
                     .groups = "drop")

  # for each country1, find the mean of dist if group1 != group2
  neighbour_vals <- dist_data |>
    dplyr::filter(group1 != group2) |>
    dplyr::group_by(country1, group2) |>
    dplyr::summarise(avg_dist = mean(dist, na.rm = TRUE),
                     .groups = "drop")

  # select the group with the min avg_dist
  b_vals <- neighbour_vals |>
    dplyr::group_by(country1) |>
    dplyr::summarise(neighbour = group2[which.min(avg_dist)],
                     b = min(avg_dist, na.rm = TRUE),
                     .groups = "drop")

  # calculate the silhouette score of each country
  sil_scores <- country_avg_dist |>
    dplyr::left_join(a_vals, dplyr::join_by("country1")) |>
    dplyr::left_join(b_vals, dplyr::join_by("country1")) |>
    dplyr::mutate(sil_width = dplyr::if_else(is.na(a),
                                  0, # if a is NA, set sil_width = 0
                                  ((b - a)/ pmax(a, b)))) |> #parrallel max value btw a and b
    dplyr::select(country1, country_avg_dist, group1,
                  group_avg_dist = a, neighbour, sil_width)


  return(sil_scores)
}
