if(getRversion() >= "3.5") utils::globalVariables("group")

#' Compute the set of diagnostic indices
#'
#' Calculates the collection of diagnostic indices at once
#'
#' @param wdi_data A data frame of the indicator data generated by \code{\link{get_wdi_data}}
#' @param index An optional character string specifying the indicator code
#' Defaults to `NULL`
#' @param group_var A grouping variable in the WDI data set (e.g., "region" or "income")
#'
#' @returns A data frame with columns `country`, `country_avg_dist`, `within_group_dist`, `sil_width`,
#' `trend_strength`, `linearity`, `curvature`, `smoothness`, `crossing_points`, `flat_spot`, and `acf`.
#' @export
#'
#' @examples
#' pm_data <- get_wdi_data(indicator = "EN.ATM.PM25.MC.M3")
#' pm_diagnostic_metrics <- compute_diagnostic_indices(pm_data, group_var = "region")
compute_diagnostic_indices <- function(wdi_data, index = NULL, group_var) {
  # Identify the name of the variable in the wdi data that contains the country-year value as index
  if(is.null(index)) {
    index_var <- attr(wdi_data, "index_var")
    index = index_var[1]
  }

  # filter valid data using the `get_valid_data()` function
  invisible(utils::capture.output(
    valid_data <- get_valid_data(wdi_data)
  ))

  # compute variation
  variation <- compute_variation(wdi_data, group_var = group_var)

  # compute trend and shape measures
  trend_shape <- compute_trend_shape_features(wdi_data)

  # compute sequential measures
  sequential <- compute_temporal_features(wdi_data)

  combine_measures <- variation |>
    dplyr::select(-group) |>
    dplyr::left_join(trend_shape, by = "country") |>
    dplyr::left_join(sequential, by = "country")


  return(combine_measures)
}
