utils::globalVariables(c(".data", "metrics", "diagnostics"))


#' Plot distribution(s) of diagnostic metric(s)
#'
#' Generates faceted `ggplot` displaying the distribution of either selected metric(s) or all the set of diagnostic indices.
#' By default, distribution(s) are ungrouped; if a `group_var` is specified, distributions are grouped by its levels within each panel.
#' If only one metric is specified in `metric_var`, a single panel is displayed.
#'
#' @param metric_summary A data frame containing computed diagnostic metrics and the pre-defined grouping information,
#' generated by passing the output of any diagnostic metrics function to \code{\link{add_group_info}}
#' @param colour_var A variable in `metric_summary` data frame whose levels are mapped to distinct colours in the resulting plot
#' @param metric_var Character string or vector of character strings specifying metric variable name(s) in `metric_summary` to plot
#' If `NULL` (default), distributions are plotted for all metric variables in `metric_summary`
#' Is specified, only the distribution for the specified metric(s) will be plotted
#' @param group_var A grouping variable in the WDI data set (e.g., "region" or "income")
#' Default to `NULL`
#' If `NULL`, distributions are ungrouped and if specified, distributions are grouped by the levels of the variable
#' @returns A `ggplot` object displaying either the ungrouped or grouped distribution of metric(s) in `metric_summary`.
#' Each metric is displayed in a separate facet panel; if one metric is specified, a single panel is shown.
#' @export
#'
#' @examples
#' pm_data <- get_wdi_data(indicator = "EN.ATM.PM25.MC.M3")
#' pm_diagnostic_metrics <- compute_diagnostic_indices(pm_data, group_var = "region")
#' pm_diagnostic_metrics_group <- add_group_info(metric_summary = pm_diagnostic_metrics,pm_data)
#' plot_metric_distribution(pm_diagnostic_metrics_group, colour_var = "region", group_var = "region")
plot_metric_distribution <- function(metric_summary, colour_var, metric_var = NULL, group_var = NULL){
  # diagnostic summary could either be the output of the diagnostic indices or a collection of the features

  if(is.null(metric_var)){
    # pivot_long all the metric summaries
    summary_long <- metric_summary |>
      tidyr::pivot_longer(
        -c(country, region, income),
        names_to = "diagnostics",
        values_to = "metrics"
      ) |>
      dplyr::mutate(
        diagnostics = factor(diagnostics, levels = unique(diagnostics))
      )
  } else{
    # one or more selected features
    summary_long <- metric_summary |>
      tidyr::pivot_longer(
        c(tidyselect::all_of(metric_var)),
        names_to = "diagnostics",
        values_to = "metrics"
      ) |>
      dplyr::mutate(
        diagnostics = factor(diagnostics, levels = unique(diagnostics)),

      )
  }
  # the plots
  if(is.null(group_var)){
    # ungrouped plot
    P <- summary_long |>
      ggplot2::ggplot(
        ggplot2::aes(
          x = metrics, fill = forcats::fct_infreq(.data[[colour_var]]),
          group = NA, order = forcats::fct_infreq(.data[[colour_var]]))
      ) +
      ggdist::geom_dots(slab_color = NA) +
      ggplot2::facet_wrap(~diagnostics, scales = "free") +
      ggplot2::labs(x = "Metric Values", y = "", fill = colour_var) +
      ggplot2::theme(
        axis.text.y = ggplot2::element_blank(),
        axis.ticks.y = ggplot2::element_blank(),
        legend.position = "bottom"
      )
  } else{
    # grouped plot
    P <- summary_long |>
      ggplot2::ggplot(
        ggplot2::aes(
          x = metrics, y = forcats::fct_infreq(.data[[group_var]]),
          fill = forcats::fct_infreq(.data[[colour_var]]), group = NA, order = .data[[group_var]])
      ) +
      ggdist::geom_dots(slab_color = NA) +
      ggplot2::facet_wrap(~diagnostics, scales = "free") +
      ggplot2::labs(x = "Metric Values", y = "", fill = colour_var) +
      ggplot2::theme(
        axis.text.y = ggplot2::element_blank(),
        axis.ticks.y = ggplot2::element_blank(),
        legend.position = "bottom"
      )
  }
  return(P)
}
