#' Plot of diagnostic metrics linked to data trajectories
#'
#' Creates an interactive plot linking the scatterplot of two selected metrics with data trajectories.
#' The scatterplot showing the relationship between specified metrics are presented in one panel,
#' and the data trajectories are presented in another panel.
#' Hovering over a point in the scatterplot highlights the corresponding trajectory with the country name, and vice versa.
#'
#' @param wdi_data A data frame of the indicator data generated by \code{\link{get_wdi_data}}
#' @param index A character string specifying the indicator code
#' Defaults to `NULL`
#' @param metric_summary A data frame containing computed diagnostic metrics and the pre-defined grouping information,
#' generated by passing the output of any diagnostic metrics function to \code{\link{add_group_info}}
#' @param metric_var A vector of character strings specifying metric variable names in `metric_summary`
#' @param group_var A grouping variable in the WDI data set (e.g., "region" or "income")
#' Default to `NULL`
#' If `NULL`, both plots are ungrouped and if specified, they are grouped by the levels of the specified grouping variable
#'
#' @returns An ungrouped or grouped interactive `girafe` object displaying the two panels, one with the scatterplot of two specified metrics and the other with the data trajectories.
#'
#' @export
#'
#' @examples
#' pm_diagnostic_metrics <- compute_diagnostic_indices(pm_data, group_var = "region")
#' pm_diagnostic_metrics_group <- add_group_info(metric_summary = pm_diagnostic_metrics,pm_data)
#' plot_metric_linkview(pm_data, metric_summary = pm_diagnostic_metrics,
#' metric_var = c("linearity", "curvature"))
plot_metric_linkview <- function(wdi_data, index = NULL, metric_summary, metric_var, group_var = NULL) {
  # Identify the name of the variable in the wdi data that contains the country-year value as index
  if(is.null(index)) {
    index_var <- attr(wdi_data, "index_var")
    index = index_var[1]
  }

  # filter valid countries and years where actual data were collected, ignoring the WDI defaults
  # using the `get_valid_data()` function
  invisible(utils::capture.output(
    valid_data <- get_valid_data(wdi_data, index = index)
  ))

  if(is.null(group_var)){
    # the line plot
    line_plot <- ggplot2::ggplot() +
      ggiraph::geom_line_interactive(
        data = valid_data,
        ggplot2::aes(
          x = .data$year,
          y = .data[[index]],
          group = .data$country,
          tooltip = .data$country,
          data_id = .data$country
        ),
        color = "grey35"
      ) +
      ggplot2::theme_minimal() +
      ggplot2::theme(legend.position = "none")

    # dot plot
    dot_plot <- metric_summary |>
      ggplot2::ggplot() +
      ggiraph::geom_point_interactive(
        ggplot2::aes(
          x = .data[[metric_var[[1]]]],
          y = .data[[metric_var[[2]]]],
          tooltip = .data$country,
          data_id = .data$country
        ),
        position = ggplot2::position_jitter(height = 0.2),
        color = "grey25"
      ) +
      ggplot2::theme_minimal()
  } else{
    line_plot <- ggplot2::ggplot() +
      ggiraph::geom_line_interactive(
        data = valid_data,
        ggplot2::aes(
          x = .data$year,
          y = .data[[index]],
          group = .data$country,
          tooltip = .data$country,
          data_id = .data$country
        ),
        color = "grey35"
      ) +
      ggplot2::facet_wrap(~.data[[group_var]], ncol = 2) +
      ggplot2::theme_minimal() +
      ggplot2::theme(legend.position = "none")

    # dot plot
    dot_plot <- metric_summary |>
      ggplot2::ggplot() +
      ggiraph::geom_point_interactive(
        ggplot2::aes(
          x = .data[[metric_var[[1]]]],
          y = .data[[metric_var[[2]]]],
          tooltip = .data$country,
          data_id = .data$country
        ),
        position = ggplot2::position_jitter(height = 0.2),
        color = "grey25"
      ) +
      ggplot2::facet_wrap(~.data[[group_var]], ncol = 2) +
      ggplot2::theme_minimal()
  }

  # Create interactive plot with girafe
  ggiraph::girafe(ggobj = patchwork::wrap_plots(dot_plot, line_plot),
                  width_svg = 9.5,
                  height_svg = 6,
                  options = list(
                    ggiraph::opts_hover_inv(css = "opacity: 0.2;")  # makes non-hovered lines fade
                  ))
}
