#' Plot of diagnostic metrics parallel coordinate plot
#'
#' Generates interactive parallel coordinate plots of all diagnostic indices.
#' Hovering over a line across x-axis displays the country name, corresponding metric and its metric value.
#'
#' @param diagnostic_summary A data frame containing the computed set of diagnostic indices generated by \code{\link{compute_diagnostic_indices}}
#' @param colour_var A variable in `metric_summary` data frame whose levels are mapped to distinct colours in the resulting plot
#' @param group_var A grouping variable in the WDI data set (e.g., "region" or "income")
#' Default to `NULL`
#' If `NULL`, parallel coordinates are ungrouped and if specified, parallel coordinates are grouped by the levels of the specified grouping variable
#'
#' @returns An ungrouped or grouped interactive parallel coordinate plot of all diagnostic metrics, with each metric represented as a vertical axis.
#'  Each country is shown as an interactive line that intersects all axes, with the position along the x-axis corresponding to the diagnostic indices.
#'
#' @export
#'
#' @examples
#' pm_diagnostic_metrics <- compute_diagnostic_indices(pm_data, group_var = "region")
#' pm_diagnostic_metrics_group <- add_group_info(metric_summary = pm_diagnostic_metrics,pm_data)
#' plot_parallel_coords(pm_diagnostic_metrics_group, colour_var = "region", group_var = "region")
plot_parallel_coords <- function(diagnostic_summary, colour_var, group_var = NULL){

  # pivot_long all the metric summaries
  summary_long <- diagnostic_summary |>
    tidyr::pivot_longer(
      -c(.data$country, .data$region, .data$income),
      names_to = "diagnostics",
      values_to = "metrics"
    )


  # scale the metrics
  if(is.null(group_var)){
    # the ungrouped parallel coordinate plot
    summary_long$metrics_norm <- NULL
    # scale the metrics - global normalisation
    scaled_metrics <- summary_long |>
      dplyr::group_by(.data$diagnostics) |>
      dplyr::mutate(
        metrics_norm = scales::rescale(.data$metrics, to = c(0, 1),
                                       na.rm = TRUE)) |>
      dplyr::ungroup() |>
      dplyr::mutate(
        diagnostics = factor(.data$diagnostics,
                             levels = unique(.data$diagnostics))
      )

    P <- scaled_metrics |>
      ggplot2::ggplot() +
      ggiraph::geom_point_interactive(
        ggplot2::aes(
          x = .data$diagnostics,
          y = .data$metrics_norm,
          group = .data$country,
          color = .data[[colour_var]],
          tooltip = paste(
            "Country:", .data$country, "<br/>",
            .data$diagnostics, ":", sprintf("%.2f", .data$metrics)),
          data_id = .data$country
        ),
        alpha = 0.3, size = 0.8
      ) +
      ggiraph::geom_line_interactive(
        ggplot2::aes(
          x = .data$diagnostics,
          y = .data$metrics_norm,
          group = .data$country,
          color = .data$region,
          tooltip = .data$country,
          data_id = .data$country
        ), alpha = 0.6
      ) +
      ggplot2::scale_x_discrete(expand = c(0, 0.2)) +
      ggplot2::labs(x ="diagnostic indices", y = " ") +
      ggplot2::theme_minimal() +
      ggplot2::theme(
        axis.text.x = ggplot2::element_text(angle = 25, hjust = 0.7, size = 4),
        legend.title = ggplot2::element_blank(),
        legend.position = "bottom"
      )
  } else{
    # scale the metrics - group-wise normalisation
    scaled_metrics <- summary_long |>
      dplyr::group_by(.data[[group_var]], .data$diagnostics) |>
      dplyr::mutate(
        metrics_norm = scales::rescale(.data$metrics, to = c(0, 1),
                                       na.rm = TRUE)) |>
      dplyr::ungroup() |>
      dplyr::mutate(
        diagnostics = factor(.data$diagnostics,
                             levels = unique(.data$diagnostics))
      )
    # the grouped parallel coordinate plot
    P <- scaled_metrics |>
      ggplot2::ggplot() +
      ggiraph::geom_point_interactive(
        ggplot2::aes(
          x = .data$diagnostics,
          y = .data$metrics_norm,
          group = .data$country,
          color = .data[[group_var]],
          tooltip = paste(
            "Country:", .data$country, "<br/>",
            .data$diagnostics, ":", sprintf("%.2f", .data$metrics)),
          data_id = .data$country
        ),
        alpha = 0.3, size = 0.8
      ) +
      ggiraph::geom_line_interactive(
        ggplot2::aes(
          x = .data$diagnostics,
          y = .data$metrics_norm,
          group = .data$country,
          color = .data$region,
          tooltip = .data$country,
          data_id = .data$country
        ), alpha = 0.6
      ) +
      ggplot2::facet_wrap(~.data[[group_var]]) +
      ggplot2::scale_x_discrete(expand = c(0, 0.2)) +
      ggplot2::labs(x ="diagnostic indices", y = " ") +
      ggplot2::theme_minimal() +
      ggplot2::theme(
        axis.text.x = ggplot2::element_text(angle = 25, hjust = 0.7, size = 4),
        legend.title = ggplot2::element_blank(),
        legend.position = "bottom"
      )
  }

  # the interactive hover plot with girafe
  ggiraph::girafe(ggobj = P,
                  width_svg = 10,
                  height_svg = 6,
                  options = list(
                    use_cursor_pos = FALSE,
                    ggiraph::opts_hover_inv(css = "opacity: 0.1;"), # makes non-hovered lines fade
                    ggiraph::opts_hover(css = "opacity: 1; stroke-width: 1.5;") #on hover: no color change
                  ))
}
