#' Plot of metric values partitioned by grouping variable
#'
#' Generates bars representing the metric value of each country, countries are partitioned by the levels of a specified variable.
#' The partition plot is restricted to group levels containing more than one country, because meaningful comparisons are not possible for single-country levels.
#' The metric value of each country is represented by a coloured bar ordered in descending order, while a lighter-shaded rectangular bar beneath indicates the group-level average for the metric.
#' Countries in each group-level are represented by the same colour.
#'
#' @param metric_summary A data frame containing computed diagnostic metrics and the pre-defined grouping information,
#' generated by passing the output of any diagnostic metrics function to \code{\link{add_group_info}}
#' @param metric_var Character string specifying metric variable name in `metric_summary` to plot
#' @param group_var A grouping variable in the WDI data set (e.g., "region" or "income")
#' @param x_breaks Numeric vector specifying the limits and breaks, default to NULL which automatically breaks the x_axis
#'
#' @returns A `ggplot` object displaying the metric value of each country by a coloured bar ordered in descending order.
#' A lighter-shaded rectangular bar is displayed beneath the bars indicating their respective group-level average.
#' @export
#'
#' @examples
#' pm_diagnostic_metrics <- compute_diagnostic_indices(pm_data, group_var = "region")
#' pm_diagnostic_metrics_group <- add_group_info(metric_summary = pm_diagnostic_metrics,pm_data)
#' plot_metric_partition(metric_summary = pm_diagnostic_metrics_group,
#' metric_var = "sil_width", group_var = "region")
plot_metric_partition <- function(metric_summary, metric_var, group_var, x_breaks = NULL){

  # define colour pallete for the group_var levels
  group_levels <- sort(unique(metric_summary[[group_var]]))

  group_colours <- scales::hue_pal()(length(group_levels))

  names(group_colours) <- group_levels


  group_metric <- metric_summary |>
    dplyr::group_by(dplyr::across(tidyselect::all_of(group_var))) |>
    dplyr::mutate(group_avg = mean(.data[[metric_var]])) |>
    dplyr::ungroup() |>
    # Re-order group_var by the group_avg
    dplyr::mutate(group = forcats::fct_reorder(.data[[group_var]], -.data$group_avg)) |>
    # create colours for group levels
    dplyr::mutate(
      colour = group_colours[.data[[group_var]]],
      country_label = paste0("<span style='color:", .data$colour, "'>", .data$country, "</span>")
    ) |>
    dplyr::add_count(.data[[group_var]]) |>
    dplyr::filter(.data$n > 1) |>
    dplyr::group_by(dplyr::across(tidyselect::all_of("group"))) |>
    dplyr::arrange(.data[[metric_var]], .by_group = TRUE) |>
    dplyr::mutate(country_label = forcats::fct_inorder(.data$country_label)) |>
    dplyr::ungroup()


  if(!is.null(x_breaks)){
    #compute default breaks, if not specified
    # The plot
    P <- group_metric |>
      ggplot2::ggplot() +
      # Draw group average bars in the background
      ggplot2::geom_col(
        ggplot2::aes(x = .data$group_avg, y = .data$country_label, fill = .data[[group_var]]),
        width = 1, alpha = 0.25
      ) +
      ggplot2::geom_col(
        ggplot2::aes(x = .data[[metric_var]], y = .data$country_label, fill = .data[[group_var]]),
        width = 0.75
      ) +
      ggplot2::facet_grid(ggplot2::vars(.data$group), scales = "free_y", space = "free_y", switch = "y") +
      ggplot2::scale_fill_manual(values = group_colours) +
      ggplot2::scale_x_continuous(breaks = x_breaks) +
      ggplot2::labs(x = paste0("Metric Measure: ",metric_var), y = " " ) +
      ggplot2::theme(
        axis.text.y = ggtext::element_markdown(size = 6),
        axis.ticks.y = ggplot2::element_blank(),
        legend.position = "none",
        panel.spacing = grid::unit(0.05, "lines"),
        strip.text.y.left = ggplot2::element_text(hjust = 1, angle = 0),
        strip.background = ggplot2::element_rect(fill = "white"),
        strip.placement = "outside"
      )
  } else {

  # The plot
  P <- group_metric |>
    ggplot2::ggplot() +
    # Draw group average bars in the background
    ggplot2::geom_col(
      ggplot2::aes(x = .data$group_avg, y = .data$country_label, fill = .data[[group_var]]),
      width = 1, alpha = 0.25
    ) +
    ggplot2::geom_col(
      ggplot2::aes(x = .data[[metric_var]], y = .data$country_label, fill = .data[[group_var]]),
      width = 0.75
    ) +
    ggplot2::facet_grid(ggplot2::vars(.data$group), scales = "free_y", space = "free_y", switch = "y") +
    ggplot2::scale_fill_manual(values = group_colours) +
    ggplot2::labs(x = paste0("Metric Measure: ",metric_var), y = " " ) +
    ggplot2::theme(
      axis.text.y = ggtext::element_markdown(size = 6),
      axis.ticks.y = ggplot2::element_blank(),
      legend.position = "none",
      panel.spacing = grid::unit(0.05, "lines"),
      strip.text.y.left = ggplot2::element_text(hjust = 1, angle = 0),
      strip.background = ggplot2::element_rect(fill = "white"),
      strip.placement = "outside"
    )
  }

  # converting the ggplot to a graphical object

  G <- ggplot2::ggplotGrob(P)

  stripl <- which(grepl('strip-l', G$layout$name))  #the strip names has been switch to the left, hence the reason for the strip-l

  # let's extract the default colour scheme used by geom_col
  # Build the ggplot to extract fill colours
  built <- ggplot2::ggplot_build(P)

  # Extract fill colours from the first layer (group_avg bars) and
  # adding the default fill colour to the panel_groups
  default_colours <- built$data[[1]] |>
    dplyr::select("PANEL", "fill") |>
    dplyr::distinct()

  panel_groups <- built$layout$layout |>
    dplyr::select("PANEL", "group")

  fill_colours <- panel_groups |>
    dplyr::left_join(default_colours, by = "PANEL")


  for (i in stripl){
    j <- which(grepl('rect', G$grobs[[i]]$grobs[[1]]$childrenOrder))
    k <- which(grepl('text', G$grobs[[i]]$grobs[[1]]$childrenOrder))
    grobtext <- G$grobs[[i]]$grobs[[1]]$children[[k]]$children[[1]]$label
    st <- match(gsub("\n", " ", grobtext), fill_colours$group)
    if (!is.na(st)){
      r <- which(grepl('text', G$grobs[[i]]$grobs[[1]]$children[[k]]$childrenOrder))
      G$grobs[[i]]$grobs[[1]]$children[[k]]$children[[r]]$gp$col <- fill_colours$fill[st]
    }
  }

  grid::grid.draw(G)
}
